name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fb55d3b7c59a8b977ad4dbac48e361417d79cc68c888313a157df252105416a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
