name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51c7fa5ac036e50edf3a0936d328d7c9ddbc74984ead2d818d8e1db911d0fce5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
