name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03b0feaf7c7c3c5045cf59baa1d7a06df990ddd6c32e8bf50fbbd2265b9c2e75"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
