name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1abd98b191a6650e50bf6f421b3ce51c0c2b45537c60957ad9e0eda9ba97b313"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
