name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "084d8ea547634d6f51c62b940633760b7f9838c509b395667acbced06112c5ec"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
