name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d641b975548b249eb0ce86d1564beabb98ea8268897c00c85fb395e0e8d07911"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
