name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78e533d0b7fb6c99c9faee7307847025d79151491e7b8ca1ca3068351e22a99e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
