name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fa74b2c685d7035713f9d5a2084cb05c1846752a5cd906ea65cdaba7c4cc322"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
