name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fca1c13b4b7420d057688d14542f134ff7286be201aa4553fc501b8b62b89361"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
