name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fd6a6aed83cc3a9f94bf97b63d3b26a5bd4f656a99f9e534bdf7151d7c0dbe4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
