name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dd1bf6964d7b66b9d54e479a93daaa240ffbaf45c5e9f58b93df8739a435689"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
