name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8d6447bc3f84c56a8501f8e7eefc1b5860c23f3f46372f8d168d29abeb518c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
