name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dac4d7a199e1ee0b7a175173b83ba0d11b6d3d3ff4af318439e98665c499215"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
