name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e99910e86b2b342b9e269f720d4a07bd872e130c90ffdc642b2ad21fa259fb5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
