name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ebd240bfe905d33bce6f58a0ac7f62a271fecd6ce8b46af84f8a63a18e5589"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
