name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12fa75e13fb6c1e1aa24bb3bab8230fe7fc340cac6e7368ccdaa638a819b2700"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
