name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ddc97cfc341ed6de1dea392962f7baff4eb8cbb1d3b8ecfde79e2fc8f896272"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
