name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63612b16d9db0c6bb2fcfe663b2cb250c1f7c3cbda342605fd112f7ac00e53cf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
