name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40be66d0ca142ee8fa9f4ed1375b183e82d089571e81653afcc1f5bff321ca89"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
