name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1125a778f788d4ea4e5c6ac9482a5fe4ca54b1938868fd47fab304c41113d0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
