name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2295d65c9363cfbb769f127ecbc16a35afe23bd469b1425066446df9dfdb67bb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
