name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd442e06f1f0d21894518ccf0f019ff12e90b4c53edb7bcb0a8a551ae24d08ca"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
