name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbf2490adbef87ce2084071ac5ac95a212716a7398c0c40d5bd8b4358513212d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
