name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d60329f8fe0dd347ae427856d6058266c79e4dad9213ca7df39fcb762d54e6bf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
