name = "Dartis-Craft - Ruins of the Ancients 2 Packwiz"
author = "Dartis Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec2b113a86ea7a600fe510b52ebdeaad47909afa1a7d6e47ecb398b4c91859a5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
